# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RoomieDataTester' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RoomieDataTester
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Firestore'

  target 'RoomieDataTesterTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RoomieDataTesterUITests' do
    inherit! :search_paths
    # Pods for testing
  end


end
